import {
  MinimumTax,
  NetWealthLastDate,
  RepairCollection,
  EmploymentType,
  IncomeFromEmployment,
  TransportCCType,
  ResidentialStatus,
  AssesseeStatus,
  SpecialBenefits,
} from "@prisma/client";

import z from "zod";

const govtPayScaleSchema = z.object({
  amount: z.string().nullable().optional(),
  taxExempted: z.string().nullable().optional(),
  taxable: z.string().nullable().optional(),
});

const personalExpenseSchema = z.object({
  amount: z.string().nullable().optional(),
  comment: z.string().nullable().optional(),
});

const incomeFromCapitalGainsSchema = z.object({
  description: z.string().optional(),
  capitalGain: z.string().nullable().optional(),
  exemptedAmount: z.string().nullable().optional(),
  taxableAmount: z.string().nullable().optional(),
});

const financialAssetsSchema = z.object({
  description: z.string().optional(),
  balance: z.string().nullable().optional(),
  interestProfit: z.string().nullable().optional(),
  sourceTax: z.string().nullable().optional(),
});

// Define the Zod schema
export const individualTaxReturnSchema = z.object({
  // Image 1
  taxpayerName: z.string().min(2, "Name must be at least 2 characters"),
  nationalId: z
    .string()
    .min(10, "National ID or Passport number must be at least 10 characters"),
  tin: z
    .string()
    .min(12, "TIN must be 12 characters")
    .max(12, "TIN must be 12 characters"),
  circle: z.string().min(2, "Circle must be at least 2 characters"),
  zone: z.string().min(2, "Zone must be at least 2 characters"),
  assessmentYear: z.string(),
  residentialStatus: z.nativeEnum(ResidentialStatus),
  assesseeStatus: z.nativeEnum(AssesseeStatus),
  specialBenefits: z.nativeEnum(SpecialBenefits).optional(),
  isParentOfDisabledPerson: z.boolean().optional(),
  dateOfBirth: z.date(),
  spouseName: z.string().optional(),
  spouseTin: z.string().optional(),
  addressLine1: z.string().min(5, "Address must be at least 5 characters"),
  addressLine2: z.string().optional(),
  telephone: z.string().optional(),
  mobile: z.string().min(11, "Mobile number must be at least 11 characters"),
  email: z.string().email("Please enter a valid email address"),
  employerName: z.string().optional(),
  businessName: z.string().optional(),
  bin: z.string().optional(),
  partnersMembersAssociation1: z.string().optional(),
  partnersMembersAssociation2: z.string().optional(),

  // Image 2
  statementOfIncomeYearEndedOn: z.date(),
  incomeFromEmployment: z.string().optional(),
  incomeFromRent: z.string().optional(),
  incomeFromAgriculture: z.string().optional(),
  incomeFromBusiness: z.string().optional(),
  incomeFromCapitalGains: z.string().optional(),
  incomeFromFinancialAssets: z.string().optional(),
  incomeFromOtherSources: z.string().optional(),
  shareOfIncomeFromAOP: z.string().optional(),
  incomeOfMinor: z.string().optional(),
  taxableIncomeFromAbroad: z.string().optional(),
  totalIncome: z.string().optional(),
  totalAmountPayable: z.string().optional(),
  minimumTax: z.nativeEnum(MinimumTax),
  netWealthSurcharge: z.string().optional(),
  taxPayable: z.string().optional(),
  environmentalSurcharge: z.string().optional(),
  totalSurcharge: z.string().optional(),
  delayInterest: z.string().optional(),
  grossTaxOnTaxableIncome: z.string().optional(),
  netTaxAfterRebate: z.string().optional(),
  minimumTaxAmount: z.string().optional(),

  // Image 3
  taxDeductedOrCollected: z.string().optional(),
  advanceTaxPaid: z.string().optional(),
  adjustmentOfTaxRefund: z.string().optional(),
  taxPaidWithThisReturn: z.string().optional(),
  totalTaxPaidAndAdjusted: z.string().optional(),
  excessPayment: z.string().optional(),
  taxExemptedTaxFreeIncome: z.string().optional(),
  listOfDocumentsFurnishedWithThisReturn1: z.string().optional(),
  listOfDocumentsFurnishedWithThisReturn2: z.string().optional(),
  fatherOrHusband: z.string(),
  placeOfSignature: z.string().optional(),
  signature: z.string().optional(),
  dateOfSignature: z.date(),

  // Image 4 -
  isIncomeFromEmployment: z.nativeEnum(IncomeFromEmployment),
  typeOfEmployment: z.nativeEnum(EmploymentType).nullable().optional(),
  // govt
  basicPayGovt: govtPayScaleSchema,
  arrearPayGovt: govtPayScaleSchema,
  specialAllowanceGovt: govtPayScaleSchema,
  houseRentAllowanceGovt: govtPayScaleSchema,
  medicalAllowanceGovt: govtPayScaleSchema,
  conveyanceAllowanceGovt: govtPayScaleSchema,
  festivalAllowanceGovt: govtPayScaleSchema,
  allowanceForSupportStaffGovt: govtPayScaleSchema,
  leaveAllowanceGovt: govtPayScaleSchema,
  honorariumRewardGovt: govtPayScaleSchema,
  overtimeAllowanceGovt: govtPayScaleSchema,
  banglaNoboborshoAllowancesGovt: govtPayScaleSchema,
  interestAccruedProvidentFundGovt: govtPayScaleSchema,
  lumpGrantGovt: govtPayScaleSchema,
  gratuityGovt: govtPayScaleSchema,
  otherAllowanceGovt: govtPayScaleSchema,
  totalGovt: govtPayScaleSchema,

  // image 4 // private
  basicPayPrivate: z.string().nullable().optional(),
  allowancesPrivate: z.string().nullable().optional(),
  advanceArrearSalaryPrivate: z.string().nullable().optional(),
  gratuityAnnuityPensionOrSimilarBenefitPrivate: z
    .string()
    .nullable()
    .optional(),
  perquisitesPrivate: z.string().nullable().optional(),
  receiptInLieuOfOrInAdditionToSalaryOrWagesPrivate: z
    .string()
    .nullable()
    .optional(),
  incomeFromEmployeeShareSchemePrivate: z.string().nullable().optional(),
  accommodationFacilityPrivate: z.string().nullable().optional(),
  transportFacilityPrivate: z.string().nullable().optional(),
  transportFacilityPrivateCheck: z.boolean().optional(),
  transportFacilityPrivateVehicleCC: z.nativeEnum(TransportCCType).optional(),
  anyOtherFacilityProvidedByEmployerPrivate: z.string().nullable().optional(),
  employerContributionToProvidentFundPrivate: z.string().nullable().optional(),
  otherIncomePrivate: z.string().nullable().optional(),
  totalSalaryReceivedPrivate: z.string().nullable().optional(),
  exemptedAmountPrivate: z.string().nullable().optional(),
  totalIncomeFromSalaryPrivate: z.string().nullable().optional(),

  // Image 5
  locationDescriptionOwnershipProportionOfProperty: z.string().optional(),
  rentReceivedOrAnnualValue: z.string().optional(),
  advanceRentReceived: z.string().optional(),
  valueOfAnyBenefit: z.string().optional(),
  adjustedAdvanceRent: z.string().optional(),
  vacancyAllowance: z.string().optional(),
  totalRentValue: z.string().optional(),
  repairCollectionProperty: z.nativeEnum(RepairCollection).optional(),
  repairCollectionAmount: z.string().optional(),
  municipalOrLocalTax: z.string().optional(),
  landRevenue: z.string().optional(),
  interestMortgageCapitalCharge: z.string().optional(),
  insurancePremiumPaid: z.string().optional(),
  otherAllowableDeduction: z.string().optional(),
  taxpayersSharePercentage: z.string().optional(),
  taxpayersShareAmount: z.string().nullable().optional(),
  salesTurnoverReceiptAgriculture: z.string().optional(),
  grossProfitFromAgriculture: z.string().optional(),
  generalExpensesSellingExpenses: z.string().optional(),
  totalAdmissibleDeduction: z.string().optional(),
  netIncomeFromRent: z.string().optional(),
  netProfitFromAgriculture: z.string().optional(),

  // image 6
  // 62 inputs
  nameOfBusiness: z.string().optional(),
  natureOfBusiness: z.string().optional(),
  addressOfBusiness: z.string().optional(),
  // summary of income
  salesTurnoverReceiptsBusiness: z.string().optional(),
  purchase: z.string().optional(),
  grossProfitFromBusiness: z.string().optional(),
  generalAdministrativeSellingExpenses: z.string().optional(),
  badDebtExpense: z.string().optional(),
  netProfitFromBusinessIncome: z.string().optional(),
  // balance sheet
  cashInHandAtBank: z.string().optional(),
  inventories: z.string().optional(),
  fixedAssets: z.string().optional(),
  otherAssets: z.string().optional(),
  totalAssets: z.string().optional(),
  openingCapital: z.string().optional(),
  netProfitFromBusinessBalance: z.string().optional(),
  withdrawalsInTheIncomeYear: z.string().optional(),
  closingCapital: z.string().optional(),
  liabilities: z.string().optional(),
  totalCapitalsAndLiabilities: z.string().optional(),

  incomeFromShareTransferListedCompany: incomeFromCapitalGainsSchema,
  incomeFromCapitalGain2: incomeFromCapitalGainsSchema,
  incomeFromCapitalGain3: incomeFromCapitalGainsSchema,
  incomeFromCapitalGain4: incomeFromCapitalGainsSchema,
  incomeFromCapitalGain5: incomeFromCapitalGainsSchema,
  incomeFromCapitalGainsTotal: incomeFromCapitalGainsSchema,

  // Image 7
  shonchoyparta: financialAssetsSchema,
  profitFromShoychoyparta2: financialAssetsSchema,
  profitFromShoychoyparta3: financialAssetsSchema,
  profitFromShoychoyparta4: financialAssetsSchema,
  profitFromShoychoyparta5: financialAssetsSchema,
  profitFromShoychoyparta6: financialAssetsSchema,
  profitFromShoychoyparta7: financialAssetsSchema,
  profitFromShoychoyparta8: financialAssetsSchema,
  profitFromShoychoyparta9: financialAssetsSchema,
  profitFromShoychoyparta10: financialAssetsSchema,
  profitFromShoychoypartaTotal: financialAssetsSchema,

  interestFromSecurities: financialAssetsSchema,
  profitInterestFromGovtSecurities2: financialAssetsSchema,
  profitInterestFromGovtSecurities3: financialAssetsSchema,
  profitInterestFromGovtSecurities4: financialAssetsSchema,
  profitInterestFromGovtSecurities5: financialAssetsSchema,
  profitInterestFromGovtSecurities6: financialAssetsSchema,
  profitInterestFromGovtSecurities7: financialAssetsSchema,
  profitInterestFromGovtSecurities8: financialAssetsSchema,
  profitInterestFromGovtSecurities9: financialAssetsSchema,
  profitInterestFromGovtSecurities10: financialAssetsSchema,
  profitInterestFromGovtSecuritiesTotal: financialAssetsSchema,

  // Image 8
  lifeInsurancePremium: z.string().optional(),
  contributionToDeposit: z.string().optional(),
  investmentInGovernmentSecurities: z.string().optional(),
  investmentInSecuritiesStock: z.string().optional(),
  contributionToProvidentFund: z.string().optional(),
  selfAndEmployersContribution: z.string().optional(),
  contributionToSuperAnnuationFund: z.string().optional(),
  contributionToBenevolentFund: z.string().optional(),
  contributionToZakatFund: z.string().optional(),
  otherRebatableInvestmentContribution: z.string().optional(),
  amountOfTaxRebate: z.string().optional(),
  totalAllowableInvestmentContribution: z.string().optional(),
  totalIncomeRebateTable: z.string().optional(),
  totalAllowableInvestmentRebateTable: z.string().optional(),
  taka1000000: z.string().optional(),

  // Image 9
  expensesForFood: personalExpenseSchema,
  housingExpense: personalExpenseSchema,
  personalTransportationExpenses: personalExpenseSchema,
  utilityExpense: personalExpenseSchema,
  houseKeepingExpense: personalExpenseSchema,
  humanitiesExpense: personalExpenseSchema,
  educationExpenses: personalExpenseSchema,
  personalExpenseForLocalForeignTravel: personalExpenseSchema,
  festivalExpense: personalExpenseSchema,
  taxDeductedCollectedAtSource: personalExpenseSchema,
  interestPaid: personalExpenseSchema,
  totalExpenseIndividualPerson: personalExpenseSchema,

  // Image 10
  netWealthLastDate: z.nativeEnum(NetWealthLastDate).optional(),
  netWealthLastDateAmount: z.string().optional(),
  giftExpense: z.string().optional(),
  institutionalLiabilities: z.string().optional(),
  nonInstitutionalLiabilities: z.string().optional(),
  otherLiabilities: z.string().optional(),
  lessBusinessLiabilities: z.string().optional(),
  directorsShareholdingCompanyName1: z.string().optional(),
  directorsShareholdingCompanyName2: z.string().optional(),
  directorsShareholdingCompanyName3: z.string().optional(),
  directorsShareholdingNoOfShare1: z.string().optional(),
  directorsShareholdingNoOfShare2: z.string().optional(),
  directorsShareholdingNoOfShare3: z.string().optional(),
  directorsShareholdingCompanyValue1: z.string().optional(),
  directorsShareholdingCompanyValue2: z.string().optional(),
  directorsShareholdingCompanyValue3: z.string().optional(),

  nameOfPartnershipFirm1: z.string().optional(),
  nameOfPartnershipFirm2: z.string().optional(),
  nameOfPartnershipFirm3: z.string().optional(),
  shareOfProfit1: z.string().optional(),
  shareOfProfit2: z.string().optional(),
  shareOfProfit3: z.string().optional(),
  capitalContributed1: z.string().optional(),
  capitalContributed2: z.string().optional(),
  capitalContributed3: z.string().optional(),
  totalIncomeShownInTheReturn: z.string().optional(),
  taxExemptedIncomeAndAllowance: z.string().optional(),
  receiptOfGiftOtherReceipts: z.string().optional(),
  totalSourceOfFund: z.string().optional(),
  sumOfSourceOfFundAndPreviousYearsNetWealth: z.string().optional(),
  expenseRelatingToLifestyle: z.string().optional(),
  totalExpensesAndLoss: z.string().optional(),
  netWealthAtTheLastDateOfThisFinancialYear: z.string().optional(),
  totalLiabilitiesOutsideBusiness: z.string().optional(),
  grossWealth: z.string().optional(),
  businessCapital: z.string().optional(),
  directorsShareholdingsInTheCompanies: z.string().optional(),
  businessCapitalOfPartnershipFirm: z.string().optional(),

  // Image 11
  nonAgriculturalPropertyLandHouseProperty: z.string().optional(),
  nonAgriculturalLocationDescription1: z.string().optional(),
  nonAgriculturalLocationDescription2: z.string().optional(),
  nonAgriculturalLocationDescription3: z.string().optional(),
  nonAgriculturalLocationDescription4: z.string().optional(),
  nonAgriculturalLocationDescription5: z.string().optional(),
  nonAgriculturalValue1: z.string().optional(),
  nonAgriculturalValue2: z.string().optional(),
  nonAgriculturalValue3: z.string().optional(),
  nonAgriculturalValue4: z.string().optional(),
  nonAgriculturalValue5: z.string().optional(),
  agriculturalLocationAndDescription1: z.string().optional(),
  agriculturalLocationAndDescription2: z.string().optional(),
  agriculturalLocationAndDescription3: z.string().optional(),
  agriculturalLocationValue1: z.string().optional(),
  agriculturalLocationValue2: z.string().optional(),
  agriculturalLocationValue3: z.string().optional(),

  shareDebentureUnitCertificate: z.string().optional(),
  sanchayapatraSavingsCertificate: z.string().optional(),
  depositPensionScheme: z.string().optional(),

  loanGivenToOthersName: z.string().optional(),
  loanGiventoOthersNid: z.string().optional(),
  loansGivenToOthers: z.string().optional(),

  savingDeposit: z.string().optional(),
  providentFund: z.string().optional(),
  otherInvestmentDesc: z.string().optional(),
  otherInvestment: z.string().optional(),

  typeOfMotorVehicle1: z.string().optional(),
  typeOfMotorVehicle2: z.string().optional(),
  registrationNumber1: z.string().optional(),
  registrationNumber2: z.string().optional(),
  motorValue1: z.string().optional(),
  motorValue2: z.string().optional(),
  ornamentsDesc: z.string().optional(),
  ornamentsValue: z.string().optional(),
  furnitureAndElectronic: z.string().optional(),
  othersAssetsDesc: z.string().optional(),
  othersAssetsValue: z.string().optional(),
  bankBalance: z.string().optional(),
  cashInHand: z.string().optional(),
  otherFundDesc: z.string().optional(),
  otherFundOutsideBusiness: z.string().optional(),
  assetOutsideBangladesh: z.string().optional(),
  agriculturalProperty: z.string().optional(),
  totalFinancialAssets: z.string().optional(),
  motorVehiclesTotal: z.string().optional(),
  totalAssetslocatedInBangladesh: z.string().optional(),
  totalCashInHandsAndFundOutsideBusiness: z.string().optional(),
  totalAssetsInBangladeshAndOutsideBangladesh: z.string().optional(),

  // Image 12
  totalIncomeShown: z.string().optional(),
  totalTaxPaid: z.string().optional(),
});

export type IndividualTaxReturnFormInput = z.infer<
  typeof individualTaxReturnSchema
>;
